using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Botany.PlantAnalyzer;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Botany.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PlantAnalyzerWindow : FancyWindow
    {
        private readonly IEntityManager _entityManager;
        //private readonly SpriteSystem _spriteSystem;
        private readonly IPrototypeManager _prototypes;
        //private readonly IResourceCache _cache;

        public PlantAnalyzerWindow()
        {
            RobustXamlLoader.Load(this);

            var dependencies = IoCManager.Instance!;
            _entityManager = dependencies.Resolve<IEntityManager>();
            //_spriteSystem = _entityManager.System<SpriteSystem>();
            _prototypes = dependencies.Resolve<IPrototypeManager>();
            //_cache = dependencies.Resolve<IResourceCache>();
        }

        public void Populate(PlantAnalyzerUserMessage msg)
        {
            var target = _entityManager.GetEntity(msg.TargetEntity);

            if (target == null)
            {
                PlantSpriteView.Visible = false;

                NoDataTexture.Visible = true;

                NoPlantDataText.Visible = true;
                return;
            }

            PlantSpriteView.SetEntity(target.Value);
            PlantSpriteView.Visible = true;

            NoDataTexture.Visible = false;

            NoPlantDataText.Visible = false;

            var name = new FormattedMessage();
            name.PushColor(Color.White);
            name.AddText(Loc.GetString(msg.PlantName));
            PlantNameLabel.SetMessage(name);


            YieldLabel.Text = $"{msg.Yield} produce";

            ProductionLabel.Text = $"{msg.Production} minutes";

            MaturationLabel.Text = $"{msg.Maturation} minutes";

            PotencyLabel.Text = $"{msg.Potency/100f}kg";


            LifespanLabel.Text = $"{msg.Lifespan} minutes";

            NutrientConLabel.Text = $"{msg.NutrientCons} nutri/m";

            WaterConLabel.Text = $"{msg.WaterCons} water/m";

            HeatLabel.Text = $"{msg.IdealHeat}K";


            if (msg.AnalyzerTier > 1)
            {
                PlantStatTolerance.Visible = true;
                if (msg.ChemsBasic is not null)
                {
                    var chemString = new StringBuilder("Contains ", 256);

                    var addComma = false;
                    foreach (var chemical in msg.ChemsBasic)
                    {
                        _prototypes.TryIndex(chemical, out ReagentPrototype? reagent);

                        if (reagent == null)
                        {
                            continue;
                        }

                        if (!addComma)
                        {
                            addComma = true;
                        }
                        else
                        {
                            chemString.Append(", ");
                        }

                        chemString.Append($"[color={reagent.SubstanceColor.ToHex()}]{reagent.LocalizedName}[/color]");
                    }
                    chemString.Append('.');

                    ChemLabel.Text =  chemString.ToString();
                    ChemLabel.Visible = true;
                }
            }

        }

    }
}
